appointment/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'appointment'

urlpatterns = [
    # index for this app
    # /appointment/
    url(r'^$', views.index, name='index'),
    # /appointment/create/
    url(r'^create/$', views.create_availability, name='create_availability'),
    # /appointment/<id>/
    # detail view
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),

]

evergreen/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

"""evergreen URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    # index
    url(r'^$', TemplateView.as_view(template_name='index.html'),
        name='home'),
    # /admin/...
    url(r'^admin/', admin.site.urls),
    # /profile/...
    url(r'^profile/', include('profile.urls')),
    # /tutor/...
    url(r'^tutor/', include('tutor.urls')),
    # /appointment/...
    url(r'^appointment/', include('appointment.urls')),
    # /notification/...
    url(r'^notification/', include('notification.urls')),

    # else, the 404 page results (if debug mode is off)
]

tutor/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls import url
from . import views

app_name = 'tutor'

urlpatterns = [

    # /tutor/
    # list view
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /tutor/register/
    url(r'^register/$', views.register, name='register'),
    # /tutor/edit/
    url(r'^edit/$', views.edit, name='edit'),
    # /tutor/<id>/
    # detail view
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /tutor/<id>/review/
    # review a tutor
    url(r'^(?P<pk>[0-9]+)/review/$', views.review, name='review'),
]

appointment/models.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from tutor.models import Tutor
import datetime
from pytz import timezone
from evergreen import settings


# Appointment Model
class Appointment(models.Model):
    # The tutor
    ## Can be null to allow for deletion of their account and keeping the information of this appointment
    tutor = models.ForeignKey(Tutor, null=True, on_delete=models.SET_NULL)
    # The User
    ## same deletion status
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    # start time and date
    start_time = models.DateTimeField()
    # duration in minutes. maximum is 180 minutes.
    MAX_APPOINTMENT_DURATION_MINS = 180
    duration = models.PositiveIntegerField(validators=[MaxValueValidator(MAX_APPOINTMENT_DURATION_MINS)])
    # location TODO: maybe a location / address model field would be useful
    # can be null if the tutor wishes to use the users house
    location = models.CharField(max_length=80, null=True)
    # give the tutor the option to pick where they are available to tutor for this session
    LOCATION_CHOICES = [('TUTOR_ADDRESS', "Tutor's address"),
                        ('USER_ADDRESS', "User's address"),
                        ('OTHER', "Other")]
    location_option = models.CharField(max_length=10, choices=LOCATION_CHOICES)
    # status
    STATUS_CHOICES = [('OPEN', 'Open'),
                      ('REQUESTED', 'Requested'),
                      ('BOOKED', 'Booked'),
                      ('COMPLETED', 'Completed'),
                      ('CANCELED', 'Canceled'),
                      ('EXPIRED', 'Expired')]
    # does not actually create an ENUM in the database. TODO: if i care about this make a custom model.
    # I probably will care about this to ensure the invariant. And I cannot ensure it once I make an API so gotta
    # do this at some point
    # UPDATE:
    # Not all databases even support ENUM's so not sure where I stand on this one...
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='OPEN')

    COMMENTS_MAX_LENGTH = 500
    # Tutor Comments
    tutor_comments = models.CharField(default="No tutor comments.", max_length=COMMENTS_MAX_LENGTH)
    # User Comments
    user_comments = models.CharField(default="No user comments.", max_length=COMMENTS_MAX_LENGTH)

    def __str__(self):
        """
        :return: the string of this object as: William Reed's appointment at 05-03-2016 4:00:00 for 30 minutes
        """
        return self.tutor.user.profile.name() + "'s appointment at " + self.start_time.strftime(
            settings.DATE_FORMAT + ' ' + settings.TIME_FORMAT) + ' (UTC) for ' + str(self.duration) + ' minutes'

    def end_time(self):
        """
        :return: the ending time of this appointment
        """
        return self.start_time + datetime.timedelta(minutes=self.duration)

    def cost(self):
        """
        :return: the cost of this appointment based off the tutors rate
        """
        return self.tutor.rate / 60 * self.duration

    def overlap(self, other):
        """
        does self overlap with other?
        :param other: another appointment
        :return: boolean
        """
        if self.start_time.year == other.start_time.year and self.start_time.month == other.start_time.month \
                and self.start_time.day == other.start_time.day and self.status != "CANCELED":

            duration = other.duration
            # check if the duration of start_time overlaps with the self.start_time
            if self.start_time > other.start_time:
                delta = self.start_time - other.start_time
                if delta.seconds / 60 < duration:
                    return True
            # check reverse
            else:
                delta = other.start_time - self.start_time
                if delta.seconds / 60 < self.duration:
                    return True

        return False

    # IMPORTANT:
    # the following are various methods to alter the status to ensure invariants of the model.
    # status is not meant to be directly altered.

    def request(self, user):
        """
        Request this appointment
        :param user: the user
        :return: None
        """
        if self.status != 'OPEN':
            raise ValueError('Appointment status must be "OPEN" in order to request it.')

        self.status = 'REQUESTED'
        self.user = user

        if self.location_option == "USER_ADDRESS":
            self.location = self.user.profile.address()

        # where is this num error coming from?
        self.tutor.user.profile.recieve_notification("Requested Appointment",
                                                     insert_date_link(self,
                                                                      self.user.profile.name()
                                                                      + ' has requested your {link} for {date}',
                                                                      self.tutor.user.profile.timezone))
        self.save()

    def cancel_tutor(self):
        """
        Cancel this appointment, notify users if there is one.
        :return: None
        """
        if self.status == 'COMPLETED' or self.status == 'CANCELED' or self.status == 'EXPIRED':
            raise ValueError('Appointment status must not be "COMPLETED" or "CANCELED" or "EXPIRED" to cancel it')

        self.status = "CANCELED"
        self.save()

        # notify user if there is one
        if self.user:
            self.user.profile.recieve_notification("Cancelled Appointment",
                                                   insert_date_link(self,
                                                                    self.tutor.user.profile.name()
                                                                    + ' has cancelled your {link} for {date}',
                                                                    self.user.profile.timezone))

    def cancel_user(self):
        """
        cancelation from the user of the appointment, notify the tutor
        :return: None
        """
        if self.status != 'BOOKED':
            raise ValueError('Appointment status must be "BOOKED" in order to cancel it by the user.')

        self.status = "OPEN"

        # notify the tutor
        self.tutor.user.profile.recieve_notification("Cancelled Appointment",
                                                     insert_date_link(self,
                                                                      self.user.profile.name()
                                                                      + ' has cancelled their request for {link} on {date}',
                                                                      self.tutor.user.profile.timezone))

        self.user = None
        self.user_comments = "No user comments."

        if self.location_option == "USER_ADDRESS":
            self.location = "United States"

        self.save()

    def accept(self):
        """
        Accept the user for this appointment
        :return: None
        """
        if self.status != "REQUESTED":
            raise ValueError('Appointment status must be "REQUESTED" in order to acceot it.')

        self.status = "BOOKED"
        self.save()

        self.user.profile.recieve_notification("Accepted Appointment",
                                               insert_date_link(self,
                                                                self.tutor.user.profile.name()
                                                                + ' has accepted the {link} request for {date} !',
                                                                self.user.profile.timezone))

    def decline(self):
        """
        Decline the user for this appointment, and eliminate the user reference
        :return: None
        """
        if self.status != "REQUESTED":
            raise ValueError('Appointment status must be "REQUESTED" in order to decline it.')
        else:
            self.status = "OPEN"
            self.user.profile.recieve_notification("Declined Appointment",
                                                   insert_date_link(self,
                                                                    self.tutor.user.profile.name() +
                                                                    ' has declined the {link} request for {date}',
                                                                    self.user.profile.timezone))
            self.user = None
            self.user_comments = "No user comments."
            if self.location_option == "USER_ADDRESS":
                self.location = "United States"
            self.save()

    def expire(self):
        """
        Call on expiration of this appointment
        :return: None
        """
        if self.end_time() > timezone('UTC').localize(datetime.datetime.now()):
            raise ValueError('You cannot expire an appointment that has not ended yet.')
        else:
            if self.status == 'BOOKED' or self.status == 'COMPLETED' or self.status == 'CANCELED' \
                    or self.status == 'EXPIRED':

appointment/forms.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django import forms
from .models import Appointment
from evergreen import settings


# not using a model form bc some things are a little wonky and not 1-1 with the model from the form
#  including date / time
class AvailabilityForm(forms.Form):
    # following three fields are submitted using a datepicker anyway so max length is just a precaution
    date_format = [settings.DATE_FORMAT]
    date = forms.DateField(widget=forms.TextInput(attrs={'class': 'date start'}), required=True,
                           input_formats=date_format)
    time_format = [settings.TIME_FORMAT]
    start_time = forms.TimeField(widget=forms.TextInput(attrs={'class': 'time start'}), required=True,
                                 input_formats=time_format)
    end_time = forms.TimeField(widget=forms.TextInput(attrs={'class': 'time end'}), required=True,
                               input_formats=time_format)
    location_choice = forms.ChoiceField(choices=Appointment.LOCATION_CHOICES, required=True, widget=forms.RadioSelect())
    other_location = forms.CharField(max_length=80, required=False)
    tutor_comments = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write any additional comments here',
                                                                  'class': 'md-textarea',
                                                                  'maxlength': Appointment.COMMENTS_MAX_LENGTH, }),
                                     required=False)

    class Meta:
        fields = ('date', 'start_time', 'end_time', 'location_choice', 'other_location', 'comments')

    def clean(self):
        # TODO: make sure date is in future
        cleaned_data = super(AvailabilityForm, self).clean()

        # make sure the end is after the start
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time is None or end_time is None:
            return

        if end_time <= start_time:
            msg = 'The end of the appointment must be after the start'
            self.add_error('end_time', msg)

appointment/templates/appointment/appointment_create.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}Appointments{% endblock %}
{% block content %}
    <div class="container">
        <h2>Create Appointment Availability</h2>
        {% if success_message %}
            <div class="alert alert-success">
                <strong>{{ success_message }}</strong>
            </div>
        {% elif error_message %}
            <div class="alert alert-danger">
                <strong>{{ error_message }}</strong>
            </div>
        {% endif %}
        <hr>
        <div class="col-6 col-centered">
            <div class="card">
                <div class="card-block">
                    <form method="post">
                        {% csrf_token %}

                        <div class="row" id="dateTimePicker">
                            <div class="form-group col-4">
                                {{ availability_form.date }}
                                <label for="id_date">Date</label>
                                {% if availability_form.date.errors %}
                                    <span class="text-danger small">{{ availability_form.date.errors }}</span>
                                {% endif %}
                            </div>
                            <div class="form-group col-4">
                                {{ availability_form.start_time }}
                                <label for="id_start_time">Start Time</label>
                                {% if availability_form.start_time.errors %}
                                    <span class="text-danger small">{{ availability_form.start_time.errors }}</span>
                                {% endif %}
                            </div>
                            <div class="form-group col-4">
                                {{ availability_form.end_time }}
                                <label for="id_end_time">End Time</label>
                                {% if availability_form.end_time.errors %}
                                    <span class="text-danger small">{{ availability_form.end_time.errors }}</span>
                                {% endif %}
                            </div>
                        </div>


                        {# location choices #}
                        <div class="form-group">
                            {{ availability_form.location_choice }}
                            {% if availability_form.location_choice.errors %}
                                <div class="col-sm-offset-3 col-sm-10">
                                    <span class="text-danger small">{{ availability_form.location_choice.errors }}</span>
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            {{ availability_form.tutor_comments }}
                            <label for="id_tutor_comments">Additional Comments</label>
                            {% if availability_form.tutor_comments.errors %}
                                <div class="col-sm-offset-3 col-sm-10">
                                    <span class="text-danger small">{{ availability_form.tutor_comments.errors }}</span>
                                </div>
                            {% endif %}
                        </div>

                        <div class="text-center">
                            <button class="btn dark-primary-color" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{# scripts and stuff for the date / time picker #}
{% block scripts %}

    {# TODO: must comply with MIT license for timepicker stuff and Apache for bootstrap-datepicker #}
    {# any licenses on bootstrap? #}

    <!-- include input widgets; this is independent of Datepair.js -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css"/>
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css"/>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
    {# maybe switch this to min version #}
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>

    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/datepair.js/0.4.15/datepair.min.js"></script>
    <script type="text/javascript" language="JavaScript">

        {# Setup the proper settings for the time picker stuff #}
        $('#dateTimePicker .time').timepicker({
            'minTime': '7:00am',
            'maxTime': '11:00pm',
            'step': 15,
            'timeFormat': 'g:ia',
            'disableTextInput': true
        }).on('blur', function (e) {
            var milliseconds = datepair.getTimeDiff();
            //$('#timeEnd').timepicker('getTime')
            var THREE_HOURS = 10800000;

            if (milliseconds > THREE_HOURS) {
                $('#id_time_end').timepicker('setTime', new Date($('#id_time_start').timepicker('getTime').getTime() + THREE_HOURS));
                datepair.refresh();
            }
        });

        $('#dateTimePicker .date').datepicker({
            'format': 'm/d/yyyy',
            'autoclose': true
        });

        // initialize datepair
        var dateTimePicker = document.getElementById('dateTimePicker');
        var datepair = new Datepair(dateTimePicker);

    </script>

    {# script for other box #}
    <script type="text/javascript" language="JavaScript">
        var radioDiv = $('#id_location_choice')
        var otherRadioButton = $('#id_location_choice_2')
        radioDiv.change(function () {
            if (otherRadioButton.prop('checked')) {
                radioDiv.after('<input type="text" id="id_other_location" name="other_location" ' +
                    'placeholder="Other Location. Ex: Bohemia Public Library" required></input>');
            } else {
                {# make sure it exists before removing it #}
                var otherLocationInput = $('#id_other_location')
                if (otherLocationInput.length > 0) {
                    otherLocationInput.remove()
                }
            }
        });

    </script>

{% endblock %}

appointment/templates/appointment/appointment_detail_user.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}Appointments{% endblock %}
{% block content %}
    <div class="container">
        <h2>Appointment Overview</h2>
        {% if success_message %}
            <div class="alert alert-success">
                <strong>{{ success_message }}</strong>
            </div>
        {% endif %}
        <hr>

        <div class="row">
            <div class="col-4">
                {% with tutor=appointment.tutor %}
                    {% include 'tutor/tutor_overview_card.html' %}
                {% endwith %}
            </div>

            <div class="col">
                <div class="card card-flex">
                    <div class="card-block card-block-flex">
                        <h4 class="card-title">Appointment Information <span
                                class="badge dark-primary-color">{{ appointment.get_status_display }}</span></h4>

                        <hr class="hr-flex">
                        {# TODO: should i use a table? #}
                        <div class="row">
                            <div class="col-4 col-md-auto">
                                <p class="card-text">
                                    Date<br>
                                    Time<br>
                                    Location<br>
                                    Cost<br>
                                    Additional Comments<br>
                                </p>
                            </div>
                            <div class="col">
                                {{ appointment.start_time|date }}<br>
                                {{ appointment.start_time|time }} - {{ appointment.end_time|time }}<br>
                                {% if appointment.location_option == 'USER_ADDRESS' %}
                                    Students Address
                                {% elif appointment.location_option == 'TUTOR_ADDRESS' %}
                                    Tutors Address
                                {% else %}
                                    {{ appointment.location }}
                                {% endif %}
                                <br>
                                ${{ appointment.cost|floatformat:2 }}
                                <br>
                                {{ appointment.tutor_comments|linebreaks }}
                            </div>
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <br>
                            <div class="md-form">
                            <textarea type="text" name="user_comments" id="id_user_comments"
                                      class="md-textarea"
                                      maxlength="500"></textarea>
                                <label for="id_user_comments">Additional Comments</label>
                            </div>
                            <button class="btn dark-primary-color disabled-hover" type="submit" name="request"
                                    value="request"
                                    {% if not appointment.status == 'OPEN' %}
                                    disabled
                                    title="The appointment is not available to request."
                                    {% endif %} >Request Appointment
                            </button>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

appointment/templates/appointment/appointment_information_card.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

<div class="card">
    <div class="card-block">
        <h4 class="card-title">Information <span
                class="badge dark-primary-color">{{ appointment.get_status_display }}</span></h4>
        <hr>
        <div class="row">
            <div class="col-4 col-md-auto">
                Date<br>
                Time<br>
                Location<br>
                Cost<br>
            </div>
            <div class="col">
                {{ appointment.start_time|date }}<br>
                {{ appointment.start_time|time }} - {{ appointment.end_time|time }}<br>
                {% if appointment.location_option == 'USER_ADDRESS' %}
                    Students Address
                {% elif appointment.location_option == 'TUTOR_ADDRESS' %}
                    Tutors Address
                {% else %}
                    {{ appointment.location }}
                {% endif %}
                <br>
                ${{ appointment.cost|floatformat:2 }}<br>
            </div>
        </div>
        <br>
        <p>User Comments:<br>{{ appointment.user_comments|linebreaks }}</p>
        <p>Tutor Comments:<br>{{ appointment.tutor_comments|linebreaks }}</p>
        <button name="cancel" class="btn danger-color-dark" data-toggle="modal"
                data-target="#cancelModal"
                {% if appointment.status == "COMPLETED" or appointment.status == "CANCELED" or appointment.status == "EXPIRED" %}
                disabled
                {% endif %}
        >Cancel
        </button>
    </div>
</div>