evergreen/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

"""evergreen URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    # index
    url(r'^$', TemplateView.as_view(template_name='index.html'),
        name='home'),
    # /admin/...
    url(r'^admin/', admin.site.urls),
    # /profile/...
    url(r'^profile/', include('profile.urls')),
    # /tutor/...
    url(r'^tutor/', include('tutor.urls')),
    # /appointment/...
    url(r'^appointment/', include('appointment.urls')),
    # /notification/...
    url(r'^notification/', include('notification.urls')),

    # else, the 404 page results (if debug mode is off)
]

tutor/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls import url
from . import views

app_name = 'tutor'

urlpatterns = [

    # /tutor/
    # list view
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /tutor/register/
    url(r'^register/$', views.register, name='register'),
    # /tutor/edit/
    url(r'^edit/$', views.edit, name='edit'),
    # /tutor/<id>/
    # detail view
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /tutor/<id>/review/
    # review a tutor
    url(r'^(?P<pk>[0-9]+)/review/$', views.review, name='review'),
]

tutor/models.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.db import models
from django.contrib.auth.models import User
# stupid workaround to stop problems with circular imports
# maybe another way or stop circular imports
import appointment
from django.core.validators import MaxValueValidator, MinValueValidator


# A tutor
class Tutor(models.Model):
    # connect this to a user. If the user is deleted, delete this tutor too
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # hourly rate for the tutor
    rate = models.DecimalField(decimal_places=2, max_digits=5)
    # 1500 characters is about 250 words. should be enough
    BIO_MAX_LENGTH = 1500
    bio = models.CharField(max_length=BIO_MAX_LENGTH)

    # link to personal site or something?

    # get the list of subjects (as strings) that this tutor covers
    def subjects(self):
        tutor_subjects = Subject.objects.filter(tutor=self)
        subject_strings = []

        for subject in tutor_subjects:
            subject_strings.append(subject.name)

        return subject_strings

    # William Reed
    def __str__(self):
        return self.user.profile.name()

    # get all the reviews for this tutor
    def reviews(self):
        return Review.objects.filter(tutor=self)

    # get the numerical rating for this tutor
    def rating(self):
        all_reviews = Review.objects.filter(tutor=self)
        sum = 0

        for review in all_reviews:
            sum += review.rating

        if sum == 0:
            return 0
        else:
            return sum / len(all_reviews)

    def sessions(self):
        """
        :return: the total number of sessions this tutor has completed
        """
        return appointment.models.Appointment.objects.filter(tutor=self, status='COMPLETED').count()

    # TODO: make sure this is ordered ok
    def appointments(self):
        """
        :return:  get the 'OPEN' appointments for this tutor
        """
        return appointment.models.Appointment.objects.filter(tutor=self, status='OPEN')


# subjects of a Tutor
class Subject(models.Model):
    # connect this to a Tutor. If the tutor / user is deleted, delete this too
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    # subject name
    name = models.CharField(max_length=30)

    # William Reed - Mathematics
    def __str__(self):
        return self.tutor.user.profile.name() + ' - ' + self.name


"""
5/14/17
i think this might deserve its own app. 
Neither user / tutor deserves it more
both will need access to write, view, edit reviews

5/15/17
going to try it here. it certainly is more nested in tutors than users so maybe this isnt a bad call.
"""


# A tutor review by a user
class Review(models.Model):
    # connect this to a Tutor. If the tutor / user is deleted, delete this too
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    # the user that wrote this
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # is this review supposed to be from an anonymous author? dont show author if true
    anonymous = models.BooleanField()
    # the rating of this tutor from 1-5
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    # 1500 characters is about 250 words. should be enough
    TEXT_MAX_LENGTH = 1500
    text = models.CharField(max_length=TEXT_MAX_LENGTH)
    # date of the review
    time_stamp = models.DateTimeField(auto_now_add=True)

    # TODO: add a check to make sure only one review per user/tutor combo

    # William Reed by John Francis: 3.3/5.0
    def __str__(self):
        return self.tutor.user.profile.name() + " by " + self.user.profile.name() + ": " + str(self.rating) + "/5"

    # get the appropriate amount of stars for this review
    # easier to do here than a template
    def stars(self):
        i = self.rating
        star_string = ""

        while i > 0:
            star_string += "★"
            i -= 1

        return star_string

tutor/forms.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django import forms
from .models import Tutor, Subject, Review


class TutorForm(forms.ModelForm):
    """
    Main elements of the Tutor Form
    """
    rate = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': '24.00', }))
    bio = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'This is your resume. Be very descriptive and describe yourself to prospective pupils.',
               'class': 'md-textarea', 'maxlength': Tutor.BIO_MAX_LENGTH}))

    class Meta:
        model = Tutor
        fields = ('rate', 'bio')


class SubjectForm(forms.ModelForm):
    """
    Subject for a tutor - used as a seperate class here to be deployed in a formset
    """
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Geometry',
                                                         'required': 'true'}))

    class Meta:
        model = Subject
        fields = ('name',)


class ReviewForm(forms.ModelForm):
    """
    Review for a tutor
    """
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write your review here',
                                                        'class': 'md-textarea', 'maxlength': Review.TEXT_MAX_LENGTH, }))

    class Meta:
        model = Review
        fields = ('rating', 'text', 'anonymous')

    def save(self, commit=True, *args, **kwargs):
        """
        Custom save to take in tutor and user as kwargs
        :return: instance of the saved Review
        """
        instance = super(ReviewForm, self).save(commit=False)
        instance.tutor = kwargs.pop('tutor')
        instance.user = kwargs.pop('user')
        if commit:
            instance.save()
            self.save_m2m()
        return instance

tutor/views.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.views import generic
from .models import Tutor, Subject, Review
from appointment.models import Appointment
from django.contrib.auth.decorators import login_required
from .forms import TutorForm, SubjectForm, ReviewForm
from django.shortcuts import render, redirect
from django.forms.formsets import formset_factory
from .decorators import tutors_only
from django.shortcuts import get_object_or_404


class IndexView(generic.ListView):
    """
    Tutor index view
    """
    template_name = 'tutor/tutor_list.html'

    def get_queryset(self):
        return Tutor.objects.all()


class DetailView(generic.DetailView):
    """
    Tutor detail view
    """
    model = Tutor
    template_name = 'tutor/tutor_detail.html'


# Write a review for a tutor
def write_review(request):
    pass


def view_all_tutor_reviews(request):
    pass


@login_required
def register(request):
    tutor = request.user.profile.is_tutor()
    if tutor:
        return redirect('tutor:index')

    # create the formset
    SubjectFormSet = formset_factory(SubjectForm)

    if request.method == "POST":
        tutor_form = TutorForm(request.POST)
        if tutor_form.is_valid():
            tutor = tutor_form.save(commit=False)
            tutor.user = request.user
            tutor.save()

            subject_formset = SubjectFormSet(request.POST)
            if subject_formset.is_valid():
                for subject_form in subject_formset:
                    subject = Subject(tutor=tutor, name=subject_form.cleaned_data.get('name'))
                    subject.save()
                # success at this point
                return redirect('/tutor/' + str(tutor.pk) + '/')
        return render(request, 'tutor/tutor.html',
                      {'tutor_form': tutor_form, 'subject_formset': SubjectFormSet(request.POST),
                       'name': 'Tutor Registration'})
    else:
        data = {
            'form-TOTAL_FORMS': '1',
            'form-INITIAL_FORMS': '0',
            'form-MIN_NUM_FORMS': '1', }

        tutor_form = TutorForm
        subject_formset = SubjectFormSet(data)
        return render(request, 'tutor/tutor.html',
                      {'tutor_form': tutor_form, 'subject_formset': subject_formset, 'name': 'Tutor Registration'})


@login_required
@tutors_only
def edit(request):
    # create the formset
    SubjectFormSet = formset_factory(SubjectForm, extra=0, min_num=1)

    if request.method == "POST":
        tutor = request.user.profile.is_tutor()
        tutor_form = TutorForm(request.POST, instance=tutor)
        subject_formset = SubjectFormSet(request.POST)
        if tutor_form.is_valid() and subject_formset.is_valid():
            tutor_form.save()
            # TODO: whats the better way to do this rather than deleting them all and adding
            Subject.objects.filter(tutor=tutor).delete()
            for subject_form in subject_formset:
                subject = subject_form.save(commit=False)
                subject.tutor = tutor
                subject.save()

            return redirect('/tutor/' + str(tutor.pk) + '/')

    else:
        tutor = request.user.profile.is_tutor()
        # IDK WHAT THIS IS BUT I SAW IT ONLINE WOW
        subjects = [{'tutor': tutor, 'name': s}
                    for s in tutor.subjects()]

        tutor_form = TutorForm(instance=tutor)
        subject_formset = SubjectFormSet(initial=subjects)

    return render(request, 'tutor/tutor.html',
                  {'tutor_form': tutor_form, 'subject_formset': subject_formset, 'name': 'Edit your Tutor Profile'})


@login_required
def review(request, *args, **kwargs):
    """
    create or edit your review for a tutor
    """
    pk = kwargs.get('pk')
    # make sure tutor exists
    tutor = get_object_or_404(Tutor, pk=pk)
    user = request.user

    # make sure the user has a completed session with the tutor
    user_tutor_apps = Appointment.objects.filter(tutor=tutor, user=user, status='COMPLETED').count()
    if user_tutor_apps <= 0:
        # TODO: use messages to send an error message with it
        return redirect('tutor:detail', pk=pk)

    # editing a review or adding a new one?
    user_tutor_review = Review.objects.filter(tutor=tutor, user=user)

    # edit
    if user_tutor_review.count() > 0:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, instance=user_tutor_review.first())
            review_form.save(tutor=tutor, user=user)
            # TODO: use messages to send a success message with it
            return redirect('tutor:detail', pk=pk)
        else:
            review_form = ReviewForm(instance=user_tutor_review.first())
    # add a new
    else:
        if request.method == "POST":
            review_form = ReviewForm(request.POST)
            review_form.save(tutor=tutor, user=user)
            # TODO: use messages to send a success message with it
            return redirect('tutor:detail', pk=pk)
        else:
            review_form = ReviewForm

    return render(request, 'tutor/review.html', {'review_form': review_form, 'tutor': tutor})

tutor/templates/tutor/review.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}Review{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-5 col-centered">
            <div class="text-center">
                <h3><i class="fa fa-star"></i> Review for {{ tutor.user.profile.name }}</h3>
                <hr class="mt-2 mb-2">
            </div>
            <form method="post">
                {% csrf_token %}

                {# rating #}
                {# TODO: replace with star rating #}
                <div class="form-group">
                    {{ review_form.rating.label_tag }}
                    {{ review_form.rating }}
                    {% if review_form.rating.errors %}
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ review_form.rating.errors }}</span>
                        </div>
                    {% endif %}
                </div>

                {# Review text #}
                <div class="form-group">
                    {{ review_form.text.label_tag }}
                    {{ review_form.text }}
                    <h6 class="pull-right" id="id_char_count">char counter</h6>
                    {% if review_form.text.errors %}
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ review_form.text.errors }}</span>
                        </div>
                    {% endif %}
                </div>

                {# anonymous #}
                <div class="form-group">
                    {{ review_form.anonymous.label_tag }}
                    {{ review_form.anonymous }}
                    {% if review_form.anonymous.errors %}
                        <div class="col-sm-offset-2 col-sm-10">
                            <span class="text-danger small">{{ review_form.anonymous.errors }}</span>
                        </div>
                    {% endif %}
                </div>

                {# submit button #}
                <div class="text-center">
                    <button type="submit" class="btn dark-primary-color">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {% load staticfiles %}
    {# char count #}
    <script language="JavaScript" type="text/javascript" src="{% static 'js/char-counter.js' %}"></script>
    <script language="JavaScript" type="text/javascript">
        $('#id_char_count').charCount({
            textAreaId: 'id_text'
        });
    </script>
{% endblock %}

tutor/templates/tutor/review_card.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{# Card for a tutor's review by a User #}

<div class="card">

    {#Card content#}
    <div class="card-block">
        {# rating #}
        <p class="card-text">{{ review.stars }}</p>
        {# Text #}
        <p class="card-text">{{ review.text }}</p>
        {# author #}
        <p class="card-text">by <strong>
            {% if review.anonymous %}
                Anonymous
            {% else %}
                {{ review.user.profile.name }}
            {% endif %}
        </strong> on
            <strong>{{ review.time_stamp.month }}/{{ review.time_stamp.day }}/{{ review.time_stamp.year }} </strong></p>
    </div>
    {#/.Card content#}

</div>

tutor/templates/tutor/tutor.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}{{ name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-8 col-centered">
            <div class="text-center">
                <h3><i class="fa fa-user"></i> {{ name }}</h3>
                <hr class="mt-2 mb-2">
            </div>
            <form method="post">
                {% csrf_token %}

                {# Rate #}
                <div class="form-group">
                    <label for="id_rate">Rate</label>
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        <div class="col-3 no-padding">
                            {{ tutor_form.rate }}
                        </div>
                        {# errors if their are any #}
                    </div>
                    <div class="col-sm-offset-3 col-sm-10">
                        <span class="text-danger small">{{ tutor_form.rate.errors }}</span>
                    </div>
                </div>

                {# Bio text area #}
                <div class="form-group">
                    <label for="id_bio">Biography</label>
                    {{ tutor_form.bio }}
                    <h6 class="pull-right" id="id_char_count"></h6>
                    <div class="col-sm-offset-2 col-sm-10">
                        <span class="text-danger small">{{ tutor_form.bio.errors }}</span>
                    </div>
                </div>

                {# Subjects #}
                {{ subject_formset.management_form }}

                <label>Subjects: </label>

                {% for subject_form in subject_formset %}
                    {% for field in subject_form %}
                        <div class="subject_formset">
                            <div class="col-6 no-padding">
                                <div class="input-group form-group">
                                    {{ field }}
                                    <a class="input-group-addon fa fa-trash delete-row" onclick></a>
                                </div>
                            </div>
                            <div class="col-sm-offset-3 col-sm-10">
                                <span class="text-danger small">{{ field.errors }}</span>
                            </div>
                        </div>
                    {% endfor %}
                {% endfor %}


                {# submit button #}
                <div class="text-center">
                    <button type="submit" class="btn dark-primary-color">Submit</button>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

{% block scripts %}
    {% load staticfiles %}
    <script language="JavaScript" type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
    <script language="JavaScript" type="text/javascript" src="{% static 'js/char-counter.js' %}"></script>

    {# formset and subject stuff #}
    <script language="JavaScript" type="text/javascript">
        {# Set up the formset #}
        $('.subject_formset').formset({
            customDelete: true,
            added: addSubjectTextBox
        });

        {# random subjects to use for place holders  #}
        var subject = ["Algebra", "English", "World History", "Art", "Music Composition",
            "Computer Programming", "Trigonometry", "Calculus", "Pre-Calculus", "SAT", "ACT", "Biology",
            "Earth Science", "Health", "Chemistry", "Physics"];

        {# set a random placeholder example subject #}
        function addSubjectTextBox(row) {
            // delete icon should only appear when there is more than one
            // change the id on this
            row.find("input").attr("placeholder", subject[Math.floor(Math.random() * subject.length)]);
        }

        {# TODO: does this need to be put in a document.ready type of thing or is ok to do like this #}
        {# hide delete button on form loading so you cant delete it when there is only one #}
        {% if subject_formset|length <= 1 %}
            $('a.delete-row').hide();
        {% endif %}
    </script>

    {# handle character counter #}
    <script language="JavaScript" type="text/javascript">
        $('#id_char_count').charCount({
            textAreaId: 'id_bio'
        });
    </script>
{% endblock %}

tutor/templates/tutor/tutor_list.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}Tutors{% endblock %}

{# for each tutor make a card view. limit to 4 per row #}
{% block content %}
    <div class="container">
        <h2>Tutors</h2>
        <hr>
        <br>
        <div class="row">
            {% for tutor in object_list %}
                <div class="col-sm-3">
                    {% include 'tutor/tutor_overview_card.html' %}
                </div>
                {# end the row div if the counter is at its max #}
                {% if object_list|length == forloop.counter %}
                    </div>
                    {# if this row has 4 elements, start a new row by ending the row div and starting a new one #}
                {% elif forloop.counter|divisibleby:4 %}
                    </div>
                    <br>
                    <div class="row">
                {% endif %}
            {% endfor %}
            </div>
    </div>
{% endblock %}

tutor/templates/tutor/tutor_overview_card.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{# Overview card for the listview of tutors #}

<div class="card">

    {#Card image#}

    <div class="view overlay hm-white-slight">
        <img
                class="img-fluid"
                src="{{ tutor.user.profile.picture }}"
                alt="{{ tutor.user.name }} picture">
        <a href="{% url 'tutor:detail' tutor.id %}">
            <div class="mask waves-effect waves-light"></div>
        </a>
    </div>
    {#/.Card image#}

    {# Card content #}
    <div class="card-block">
        {#Title#}
        <a href="{% url 'tutor:detail' tutor.id %}"><h4 class="card-title">{{ tutor.user.profile.name }}</h4></a>
        {#Text#}
        <p class="card-text">
            {# Rating #}
            {{ tutor.rating }} ★</br>
            {# Uses #}
            {{ tutor.sessions }} sessions</br>
            {# Specialty Subjects #}
            {% for subject in tutor.subjects %}
                {{ subject }}
                {# add a comma if they do more than one subject #}
                {% if forloop.counter != tutor.subjects|length %},{% endif %}
            {% endfor %}
        </p>
    </div>
    {#/.Card content#}

</div>