evergreen/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

"""evergreen URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    # index
    url(r'^$', TemplateView.as_view(template_name='index.html'),
        name='home'),
    # /admin/...
    url(r'^admin/', admin.site.urls),
    # /profile/...
    url(r'^profile/', include('profile.urls')),
    # /tutor/...
    url(r'^tutor/', include('tutor.urls')),
    # /appointment/...
    url(r'^appointment/', include('appointment.urls')),
    # /notification/...
    url(r'^notification/', include('notification.urls')),

    # else, the 404 page results (if debug mode is off)
]

notification/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls import url
from . import views

app_name = 'notification'

urlpatterns = [
    # /notification/
    # list of all the notifications
    url(r'^$', views.index, name='index'),
    # /notification/send/
    # staff only link to send a notification (global or whatever)
    url(r'^send/$', views.create_notification, name='create_notification'),
]

tutor/urls.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.conf.urls import url
from . import views

app_name = 'tutor'

urlpatterns = [

    # /tutor/
    # list view
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /tutor/register/
    url(r'^register/$', views.register, name='register'),
    # /tutor/edit/
    url(r'^edit/$', views.edit, name='edit'),
    # /tutor/<id>/
    # detail view
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /tutor/<id>/review/
    # review a tutor
    url(r'^(?P<pk>[0-9]+)/review/$', views.review, name='review'),
]

notification/models.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.db import models
from django.contrib.auth.models import User


# Notification Model
## may be more appropriately named as a Message
class Notification(models.Model):
    # this user sent the message.
    ## If they delete their account keep the message
    from_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    # who has names longer than 30 chars?
    ## including so I can do things like: from Evergreen Staff
    author = models.CharField(max_length=30)
    # subject
    subject = models.CharField(max_length=50)
    # message
    message = models.CharField(max_length=500)
    # time / date
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject + ' from ' + self.author + ' on ' + str(self.time_stamp)


# keeps track of where the notification is going and if it was read
# useful to send out messages to multiple people without duplicating Notification data - only this data
class DeliveryInfo(models.Model):
    # the notification
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    # to this user
    ## if their account is deleted, delete the notification / message. no need for it
    to_user = models.ForeignKey(User, on_delete=models.CASCADE)
    # read status
    read_by_user = models.BooleanField(default=False)

    def __str__(self):
        if self.read_by_user:
            return self.notification.__str__() + ' read by ' + self.to_user.__str__()
        else:
            return self.notification.__str__() + ' unread by ' + self.to_user.__str__()

notification/views.py
# Evergreen Tutoring - A simple online tutor scheduling service
# Copyright (C) 2017 William Reed
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required


# Create your views here.

@login_required
def index(request):
    notifications = request.user.profile.notifications()
    # my hacky way to change the read reciept status after sending out the data
    try:
        return render(request, 'notification/notification_list.html', {'object_list': notifications})
    finally:
        # TODO: clean this up
        for notif_tuple in notifications:
            if not notif_tuple[0].read_by_user:
                notif_tuple[0].read_by_user = True
                notif_tuple[0].save()


@staff_member_required(login_url='/profile/login/')
def create_notification(request):
    if request.method == 'POST':
        channel = request.POST['channel']
        author = request.POST['author']
        subject = request.POST['subject']
        message = request.POST['message']
        user = request.user

        user.profile.send_notification(channel, author, subject, message)

        return render(request, 'notification/send_notification.html',
                      {'success_message': 'Notification successfully sent!'})
    else:
        return render(request, 'notification/send_notification.html')

notification/templates/notification/notification_card.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

<div class="card">
    <div class="card-block">
        <h4 class="card-title">{{ notification.1.subject }}
            {% if not notification.0.read_by_user %}
                <span class="badge dark-primary-color">New</span>
            {% endif %}
        </h4>
        <hr>
        {# only server sends messages so this should be good #}
        {% autoescape off %}
            <p class="card-text">{{ notification.1.message|linebreaks }}</p>
        {% endautoescape %}
        <p class="card-text">from <strong>{{ notification.1.author }}</strong> on
            {{ notification.1.time_stamp }}</p>
    </div>
</div>

notification/templates/notification/notification_list.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}Notifications{% endblock %}
{% block content %}
    <div class="container">
        <h2>Notifications</h2>
        <hr>

        {% load tz %}
        {% for notification in object_list %}
            {% include 'notification/notification_card.html' %}
            <br>
        {% endfor %}
    </div>
{% endblock %}

notification/templates/notification/send_notification.html
{#Evergreen Tutoring - A simple online tutor scheduling service#}
{#Copyright (C) 2017 William Reed#}
{##}
{#This program is free software: you can redistribute it and/or modify#}
{#it under the terms of the GNU General Public License as published by#}
{#the Free Software Foundation, either version 3 of the License, or#}
{#(at your option) any later version.#}
{##}
{#This program is distributed in the hope that it will be useful,#}
{#but WITHOUT ANY WARRANTY; without even the implied warranty of#}
{#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the#}
{#GNU General Public License for more details.#}
{##}
{#You should have received a copy of the GNU General Public License#}
{#along with this program.  If not, see <http://www.gnu.org/licenses/>#}

{% extends 'base.html' %}
{% block title %}Send Notification{% endblock %}
{% block content %}
    <div class="container">
        <h2>Send a Notification</h2>
        {% if success_message %}
            <div class="alert alert-success">
                <strong>{{ success_message }}</strong>
            </div>
        {% endif %}
        <hr>
        <div class="col-md-6 col-centered">
            <div class="card">
                <div class="card-block">
                    <form method="post">
                        {% csrf_token %}

                        {# Subject text-box #}
                        <div class="md-form">
                            <input name="subject" type="text" id="id_subject"
                                   class="form-control" maxlength="50" required>
                            <label for="id_subject">Subject</label>
                        </div>

                        {# Message text-area #}
                        <div class="md-form">
                            <textarea required type="text" name="message" id="id_message" class="md-textarea"
                                      maxlength="500"></textarea>
                            <label for="id_message">Message</label>
                        </div>

                        {# Author #}
                        <div class="md-form">
                            <input name="author" type="text" id="id_author"
                                   class="form-control" maxlength="30" value="Evergreen Team" required>
                            <label for="id_author">Author</label>
                        </div>

                        {# Channel radio buttons #}
                        <input type="radio" name="channel" value="ALL" required> Everyone<br>
                        <input type="radio" name="channel" value="TUTORS"> Tutors<br>
                        <input type="radio" name="channel" value="STAFF"> Staff

                        <div class="text-center">
                            <button class="btn dark-primary-color" type="submit">Submit</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}